### ISSUE TITLE
Unable to read existing xml files (create_annoset.py), Why?!!

### ISSUE THREAD

**Issue by MyVanitar** [hyh21521038/ssd-plate_detection#4]
When I run the `create_lmdbdata.sh`, I get two errors related to the `.xml `files in train and test folders.

it says:

```
annotation file: /home/hesam/Desktop/img/val/annot/0269.xml does not exist
annotation file: /home/hesam/Desktop/img/train/annot/0156.xml does not exist
```

These paths are exist in first lines of `trainval.txt` and `test.txt`. it means the program stuck in the first line.

The error comes from the `create_annoset.py` file and it seems it does not recognize `.xml` files.

It seems it does not have any problem with `.jpg` files.

**But both paths are correct and files are exist there**. Why I get this error?! very strange :-(

**Comment by hyh21521038** [comment]
@you have to make sure your path is correct.check the sh file.maybe you should try another dataset to find the bug

**Comment by VanitarNordic** [comment]
@hyh21521038 
I swear the path is correct and the files are exist there :-( I checked 100 times. I amaze why it does not get error to images but just these xml files

**Comment by VanitarNordic** [comment]
it solved. The problem was the `test_name_size.txt `should contain **both** training and test images.

**Comment by MyVanitar** [comment]
it solved:
Another question: `test_name_size.txt `should just contain the test images, or both training and test?
